### ISSUE TITLE
missing string.h

### ISSUE THREAD

**Issue by corytodd** [dom96/nimkernel#5]
Not an issue, just a question.

I can build the nakefile but trying to run the nakefile generates an error stating that string.h cannot be found. I'm pretty sure my cross compiler is fine because I can build the bare bones sample from OS dev. Any ideas on what I'm missing?

I'm thinking it is related to this line in nim.cfg: --passc:"-w -I$lib -ffreestanding -O2 -Wall -Wextra"
What should $lib resolve to?

```
/build/path/nimkernel/nimcache/stdlib_system.c:12:20: fatal error: string.h: No such file or directory
```

**Comment by dom96** [comment]
Unfortunately it sounds like Nim is including things it shouldn't. I haven't touched this code in a long time now but IIRC nothing from the C stdlib should be included.

I'll see what @Araq thinks.

**Comment by corytodd** [comment]
Hmm. This appears to be related to the gc. Setting compile flag to none makes this magically work on nim 0.13.1 (i386).

Fundamentally I think this makes sense.

**Comment by dom96** [comment]
You mean `--gc:none`?

**Comment by corytodd** [comment]
Yes, exactly that.

**Comment by dom96** [comment]
I guess `--gc:none` was implied by one of the flags before, but now it no longer is. Thank you for the PR :)
